language: python
python:
- 3.4
env:
  matrix:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=flake8
  - TOXENV=pylint
  - TOXENV=cover
install:
- pip install tox coveralls bumpversion
script: tox -v
after_success:
- if [ "$TOXENV" = 'cover' ]; then coveralls; fi
notifications:
  hipchat:
    rooms:
      secure: PafUqqru2uzvMt+lMC6zjHNskguNbvK6o8P2ChjlZ9pEqs0UNRH8gRQGAQKErRfC1baUrjz2zjfqdXFvQUIIYZS9X6h9GXReX+wfaU9/ZTCL4e/TDaauXIyVKTjSgmMsk2N9XkorDHexkrHDFOENbU5YWABbnuOcXcYTEJ/VhvM=
