language: python
python:
- 3.4
env:
- TOXENV=py33
- TOXENV=py34
- TOXENV=flake8
- TOXENV=pylint
install:
- pip install tox coveralls
script: tox -v
deploy:
  provider: pypi
  user: nikicat
  password:
    secure: i9zNWTqaqWjKp4hHVXA0wWvCFS5ic7ne3nc6WP7fanQLC5y1/tQxsnmMVN02aThfpNoCZKh82rWjs/wXXxUq5Q4egXFaOjMPoyIsb8EGHFi4y1FMW/wSnw/iBXFYruWf/k+JQz2t+dj1/EpHj4sLGMPRjANdK2+fwrDFNIlUIBs=
  distributions: sdist bdist
  on:
    tags: true
    python: 3.4
    repo: yandex-sysmon/dominator
after_success:
- coveralls
notifications:
  hipchat:
    rooms:
      secure: PafUqqru2uzvMt+lMC6zjHNskguNbvK6o8P2ChjlZ9pEqs0UNRH8gRQGAQKErRfC1baUrjz2zjfqdXFvQUIIYZS9X6h9GXReX+wfaU9/ZTCL4e/TDaauXIyVKTjSgmMsk2N9XkorDHexkrHDFOENbU5YWABbnuOcXcYTEJ/VhvM=
