# Global settings for Dominator
# Copy this file to ~/.config/dominator/settings.yaml and edit

# Directory to place config files
configvolumedir: ~/.config/dominator/config

# Directory to place data
datavolumedir: ~/.config/dominator/data

docker:
# URL for default Docker instance (could be any Docker server as well),
# it is used for building images and retrieving image ids
#    url: null
#
# Uncomment this if you want to customize your Docker registry
#    registry:
#
# Put here local registry address to speed up pull
#        url: <host:port>
#
# Replace with true if your registry doesn't support https
#        insecure: false
#
# Default namespace to use for SourceImages
#    namespace: yandex

#localship:
# FQDN for LocalShip's - used for developing. Put here some local ip
# different from 127.0.0.1/::1 that local containers could reach
#    fqdn: localhost
#
# Amount of memory to report for LocalShip
#    memory: null


# This is a list of plugins to load on start
#plugins:
#    - some.python.module.name
