# Global settings for Dominator
# Copy this file to ~/.config/dominator/settings.yaml and edit

# Directory to place config files
configvolumedir: ~/.config/dominator/config

# Directory to place data
datavolumedir: ~/.config/dominator/data

docker:
# URL for default Docker instance (could be any Docker server as well),
# it is used for building images and retrieving image ids
#    url: null
#
# Uncomment this if you want to customize your Docker registry
#    registry:
#
# Put here local registry address to speed up pull
#        url: <host:port>
#
# Replace with true if your registry doesn't support https
#        insecure: false
#
# Default namespace to use for SourceImages
#    namespace: yandex

# FQDN for LocalShip's - used for developing. Put here some local ip
# different from 127.0.0.1/::1 that local containers could reach
#localship-fqdn: localhost


# FIXME: next options should be moved to separate sub-package

username: &username !!python/object/apply:os.getenv [USER]
password: &password !!python/object/apply:os.getenv [PASSWORD]

# Openstack installations endpoints and credentials
openstack:
    haze:
        domain: haze.yandex.net
        nova:
            version: 1.1
            username: *username
            api_key: *password
            project_id: MONITORING
            auth_url: http://identity.haze.yandex-team.ru/v2.0
        keystone:
            username: *username
            password: *password
            tenant_name: MONITORING
            auth_url: http://identity.haze.yandex-team.ru/v3

    fog:
        domain: i.fog.yandex.net
        nova:
            version: 1.1
            username: *username
            api_key: *password
            project_id: Monitoring
            auth_url: https://auth.fog.yandex-team.ru/v2.0
            region_name: Yandex-Search-SAS1
            insecure: true

# Racktables endpoint and credentials
racktables:
    url: https://racktables.yandex.net/
    user: *username
    password: *password
